Add Linux arm64 release for CLI

diff --git a/.github/workflows/release-cli.yaml b/.github/workflows/release-cli.yaml
--- a/.github/workflows/release-cli.yaml
+++ b/.github/workflows/release-cli.yaml
@@ -2,51 +2,43 @@ name: "release-cli"
 
 on:
   workflow_dispatch:
-  push:
-    branches: ["cli-arm64-release"]
-  # pull_request_target:
-  #   types:
-  #     - closed
-  #   paths:
-  #     - "cli/**"
+  pull_request_target:
+    types:
+      - closed
+    paths:
+      - "cli/**"
 
 jobs:
   push-tag:
+    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && !contains(github.event.pull_request.body, 'release skip'))
     runs-on: ubuntu-20.04
     outputs:
-      version: "5.0.75"
+      version: ${{ steps.version.outputs.VERSION }}
     steps:
-      - name: "nop"
-        run: ""
-  #   if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && !contains(github.event.pull_request.body, 'release skip'))
-  #   runs-on: ubuntu-20.04
-  #   outputs:
-  #     version: ${{ steps.version.outputs.VERSION }}
-  #   steps:
-  #     - name: Checkout /buildbuddy
-  #       uses: actions/checkout@v3
-  #       with:
-  #         # We need to fetch git tags to obtain the latest cli version tag.
-  #         fetch-depth: 0
+      - name: Checkout /buildbuddy
+        uses: actions/checkout@v3
+        with:
+          # We need to fetch git tags to obtain the latest cli version tag.
+          fetch-depth: 0
 
-  #     - name: Push tag
-  #       run: |
-  #         git config --local user.email "github-actions-release-bot@users.noreply.github.com"
-  #         git config --local user.name "github-actions-release[bot]"
-  #         ./cli/release.py --auto
+      - name: Push tag
+        run: |
+          git config --local user.email "github-actions-release-bot@users.noreply.github.com"
+          git config --local user.name "github-actions-release[bot]"
+          ./cli/release.py --auto
 
-  #     - name: Get CLI version
-  #       id: version
-  #       run: |
-  #         version=$(git tag -l 'cli-v*' --sort=creatordate |
-  #           perl -nle 'if (/^cli-v(\d+\.\d+\.\d+)$/) { print $1 }' |
-  #           tail -n1)
-  #         echo $version
-  #         echo "VERSION=$version" >> "$GITHUB_OUTPUT"
+      - name: Get CLI version
+        id: version
+        run: |
+          version=$(git tag -l 'cli-v*' --sort=creatordate |
+            perl -nle 'if (/^cli-v(\d+\.\d+\.\d+)$/) { print $1 }' |
+            tail -n1)
+          echo $version
+          echo "VERSION=$version" >> "$GITHUB_OUTPUT"
 
   create-release:
     runs-on: ubuntu-20.04
-    # needs: push-tag
+    needs: push-tag
     steps:
       - name: Checkout buildbuddy-io/bazel
         uses: actions/checkout@v3
@@ -81,74 +73,74 @@ jobs:
           gh release create "$TAG" \
             --repo=buildbuddy-io/bazel --title="$TAG" --draft --notes="Release version $TAG"
 
-  # sync-plugins:
-  #   runs-on: ubuntu-20.04
-  #   needs: [push-tag, create-release]
-  #   steps:
-  #     - name: Checkout buildbuddy-io/buildbuddy
-  #       uses: actions/checkout@v3
-  #       with:
-  #         path: buildbuddy
+  sync-plugins:
+    runs-on: ubuntu-20.04
+    needs: [push-tag, create-release]
+    steps:
+      - name: Checkout buildbuddy-io/buildbuddy
+        uses: actions/checkout@v3
+        with:
+          path: buildbuddy
 
-  #     - name: Checkout buildbuddy-io/plugins
-  #       uses: actions/checkout@v3
-  #       with:
-  #         repository: buildbuddy-io/plugins
-  #         path: plugins
-  #         token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
+      - name: Checkout buildbuddy-io/plugins
+        uses: actions/checkout@v3
+        with:
+          repository: buildbuddy-io/plugins
+          path: plugins
+          token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
 
-  #     - name: Sync plugins and push version tag
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
-  #         VERSION: ${{ needs.push-tag.outputs.version }}
-  #       run: |
-  #         set -e
-  #         cd "${GITHUB_WORKSPACE}/plugins"
-  #         git checkout main
-  #         git pull
+      - name: Sync plugins and push version tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
+          VERSION: ${{ needs.push-tag.outputs.version }}
+        run: |
+          set -e
+          cd "${GITHUB_WORKSPACE}/plugins"
+          git checkout main
+          git pull
 
-  #         git config --local user.name "BuildBuddy Bot"
-  #         git config --local user.email "hello@buildbuddy.io"
+          git config --local user.name "BuildBuddy Bot"
+          git config --local user.email "hello@buildbuddy.io"
 
-  #         # Commit and push changes to cli/plugins dir from buildbuddy repo
+          # Commit and push changes to cli/plugins dir from buildbuddy repo
 
-  #         # Remove any existing plugin directories in the plugins repo.
-  #         # Note, this implementation assumes all top-level directories
-  #         # are plugin directories (except the .git directory)
-  #         EXISTING_PLUGIN_DIRS=($(find . -mindepth 1 -maxdepth 1 -type d | grep -v './\.git'))
-  #         echo "Removing existing plugin dirs:" "${EXISTING_PLUGIN_DIRS[@]}"
-  #         rm -rf "${EXISTING_PLUGIN_DIRS[@]}"
+          # Remove any existing plugin directories in the plugins repo.
+          # Note, this implementation assumes all top-level directories
+          # are plugin directories (except the .git directory)
+          EXISTING_PLUGIN_DIRS=($(find . -mindepth 1 -maxdepth 1 -type d | grep -v './\.git'))
+          echo "Removing existing plugin dirs:" "${EXISTING_PLUGIN_DIRS[@]}"
+          rm -rf "${EXISTING_PLUGIN_DIRS[@]}"
 
-  #         # Copy all top-level plugin directories to the top-level of the
-  #         # plugins repo.
-  #         PLUGIN_DIRS=($(find "${GITHUB_WORKSPACE}/buildbuddy/cli/plugins" -mindepth 1 -maxdepth 1 -type d))
-  #         cp -r "${PLUGIN_DIRS[@]}" ./
+          # Copy all top-level plugin directories to the top-level of the
+          # plugins repo.
+          PLUGIN_DIRS=($(find "${GITHUB_WORKSPACE}/buildbuddy/cli/plugins" -mindepth 1 -maxdepth 1 -type d))
+          cp -r "${PLUGIN_DIRS[@]}" ./
 
-  #         # Commit and push the plugin dirs.
-  #         git add .
-  #         commit_output=$(mktemp)
-  #         if git commit -m "Update plugins to v${VERSION}" 2>&1 | tee "${commit_output}"; then
-  #           git push
-  #         elif grep 'nothing to commit' "${commit_output}" &>/dev/null; then
-  #           echo "No plugin changes in version $VERSION"
-  #         else
-  #           echo "Commit failed; exiting"
-  #           exit 1
-  #         fi
+          # Commit and push the plugin dirs.
+          git add .
+          commit_output=$(mktemp)
+          if git commit -m "Update plugins to v${VERSION}" 2>&1 | tee "${commit_output}"; then
+            git push
+          elif grep 'nothing to commit' "${commit_output}" &>/dev/null; then
+            echo "No plugin changes in version $VERSION"
+          else
+            echo "Commit failed; exiting"
+            exit 1
+          fi
 
-  #         # Push new tag to match CLI release.
-  #         TAG="v${VERSION}"
-  #         git tag "$TAG"
-  #         git push origin "$TAG"
+          # Push new tag to match CLI release.
+          TAG="v${VERSION}"
+          git tag "$TAG"
+          git push origin "$TAG"
 
   build-artifacts:
     strategy:
       matrix:
         include:
-          # - os: ubuntu-20.04
+          - os: ubuntu-20.04
           - os: ubuntu-22.04-16cpu-arm64-arm-limited # linux arm64
-          # - os: macos-13 # MacOS amd64
-          # - os: macos-13-xlarge # MacOS arm64
+          - os: macos-13 # macOS amd64
+          - os: macos-13-xlarge # macOS arm64
     runs-on: ${{ matrix.os }}
     needs: [push-tag, create-release]
     steps:
@@ -202,12 +194,12 @@ jobs:
             "${{ steps.build.outputs.BINARY }}" \
             "${{ steps.build.outputs.BINARY }}.sha256"
 
-  # publish-release:
-  #   runs-on: ubuntu-20.04
-  #   needs: [push-tag, sync-plugins, build-artifacts]
-  #   steps:
-  #     - name: Publish release
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
-  #       run: |
-  #         gh release edit ${{ needs.push-tag.outputs.version }} --draft=false --repo=buildbuddy-io/bazel
+  publish-release:
+    runs-on: ubuntu-20.04
+    needs: [push-tag, sync-plugins, build-artifacts]
+    steps:
+      - name: Publish release
+        env:
+          GITHUB_TOKEN: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
+        run: |
+          gh release edit ${{ needs.push-tag.outputs.version }} --draft=false --repo=buildbuddy-io/bazel
