Add workflow to sync CLI plugins repo (#2777)

diff --git a/.github/workflows/release-cli.yaml b/.github/workflows/release-cli.yaml
--- a/.github/workflows/release-cli.yaml
+++ b/.github/workflows/release-cli.yaml
@@ -51,6 +51,53 @@ jobs:
           gh release create "$TAG" \
             --repo=buildbuddy-io/bazel --title="$TAG" --draft --notes="Release version $TAG"
 
+  sync-plugins:
+    runs-on: ubuntu-latest
+    needs: create-release
+    steps:
+      - name: Checkout buildbuddy-io/buildbuddy
+        uses: actions/checkout@v3
+        with:
+          path: buildbuddy
+          ref: cli-v${{ needs.create-release.outputs.VERSION }}
+      - name: Checkout buildbuddy-io/plugins
+        uses: actions/checkout@v3
+        with:
+          repository: buildbuddy-io/plugins
+          path: plugins
+          token: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
+      - name: Sync plugins and push version tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}
+          VERSION: ${{ needs.create-release.outputs.VERSION }}
+        run: |
+          set -e
+          cd "${GITHUB_WORKSPACE}/plugins"
+          git checkout main
+          git pull
+
+          git config --local user.name "BuildBuddy Bot"
+          git config --local user.email "hello@buildbuddy.io"
+
+          # Commit and push changes to cli/plugins dir from buildbuddy repo
+          rm -rf ./plugins
+          cp -r "${GITHUB_WORKSPACE}/buildbuddy/cli/plugins" ./plugins
+          git add plugins
+          commit_output=$(mktemp)
+          if git commit -m "Update plugins to v${VERSION}" 2>&1 | tee "${commit_output}"; then
+            git push
+          elif grep 'nothing to commit' "${commit_output}" &>/dev/null; then
+            echo "No plugin changes in version $VERSION"
+          else
+            echo "Commit failed; exiting"
+            exit 1
+          fi
+
+          # Push new tag to match CLI release.
+          TAG="v${VERSION}"
+          git tag "$TAG"
+          git push origin "$TAG"
+
   build-artifacts:
     strategy:
       matrix:
